// MARK: - Desktop Groups
const blueSkyDesktopGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل SocialFocus على Bluesky",
    ca: "Desactiveu SocialFocus a Bluesky",
    "zh-CN": "在 Bluesky 上禁用 SocialFocus",
    "zh-TW": "在 Bluesky 上停用 SocialFocus",
    hr: "Onemogući SocialFocus na Blueskyju",
    cs: "Zakázat SocialFocus na Bluesky",
    da: "Deaktiver SocialFocus på Bluesky",
    nl: "Schakel SocialFocus uit op Bluesky",
    en: "Disable SocialFocus on Bluesky",
    fi: "Poista SocialFocus käytöstä Blueskyssä",
    fr: "Désactiver SocialFocus sur Bluesky",
    de: "Deaktivieren Sie SocialFocus auf Bluesky",
    el: "Απενεργοποιήστε το SocialFocus στο Bluesky",
    he: "השבת את SocialFocus ב-Blusky",
    hi: "ब्लूस्काई पर सोशलफोकस अक्षम करें",
    hu: "A SocialFocus letiltása a Bluesky-n",
    id: "Nonaktifkan Fokus Sosial di Bluesky",
    it: "Disabilita SocialFocus su Bluesky",
    ja: "Bluesky で SocialFocus を無効にする",
    ko: "Bluesky에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada Bluesky",
    no: "Deaktiver SocialFocus på Bluesky",
    pl: "Wyłącz SocialFocus na Bluesky",
    pt: "Desativar SocialFocus no Bluesky",
    ro: "Dezactivați SocialFocus pe Bluesky",
    ru: "Отключить SocialFocus в Bluesky",
    sk: "Zakázať SocialFocus na Bluesky",
    es: "Deshabilitar SocialFocus en Bluesky",
    sv: "Inaktivera SocialFocus på Bluesky",
    th: "ปิดการใช้งาน SocialFocus บน Bluesky",
    tr: "Bluesky'de SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus на Bluesky",
    vi: "Tắt SocialFocus trên Bluesky",
  },
  id: "socialFocus_blueSky_master_toggle",
  defaultValue: false,
};

const blueSkyDesktopGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "بلوك بلوسكي",
      ca: "Bloqueja Bluesky",
      "zh-CN": "块蓝天",
      "zh-TW": "塊藍天",
      hr: "Blokiraj Bluesky",
      cs: "Blok Bluesky",
      da: "Bloker Bluesky",
      nl: "Blokkeer Bluesky",
      en: "Block Bluesky",
      fi: "Estä Bluesky",
      fr: "Bloquer le ciel bleu",
      de: "Blockieren Sie Bluesky",
      el: "Μπλοκ Bluesky",
      he: "בלוק בלוסקי",
      hi: "ब्लूस्काई को ब्लॉक करें",
      hu: "Blokkolja Bluesky-t",
      id: "Blokir Bluesky",
      it: "Blocca Bluesky",
      ja: "ブロック・ブルースカイ",
      ko: "블루스카이 차단",
      ms: "Sekat Bluesky",
      no: "Blokker Bluesky",
      pl: "Zablokuj Bluesky",
      pt: "Bloco Céu Azul",
      ro: "Blocați Bluesky",
      ru: "Блок Блюскай",
      sk: "Block Bluesky",
      es: "Bloquear cielo azul",
      sv: "Block Bluesky",
      th: "บล๊อกบลูสกาย",
      tr: "Bluesky'yi engelle",
      uk: "Блок Bluesky",
      vi: "Chặn Bluesky",
    },
    id: "socialFocus_blueSky_block_blueSky",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_blueSky_gray_mode",
    defaultValue: false,
  },
];

const blueSkyDesktopGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_blueSky_daily_limit_show_timer_draggable",
    defaultValue: false,
  },
];

const blueSkyDesktopGroups_Feed = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء اقتراحات الصفحة الرئيسية - اكتشف",
      ca: "Amaga els suggeriments de la pàgina d'inici - Descobreix",
      "zh-CN": "隐藏主页建议 - 发现",
      "zh-TW": "隱藏主頁建議 - 發現",
      hr: "Sakrij prijedloge početne stranice - Otkrijte",
      cs: "Skrýt návrhy domovské stránky – objevte",
      da: "Skjul forslag til startside - Opdag",
      nl: "Suggesties voor startpagina verbergen - Ontdek",
      en: "Hide Home Page Suggestions - Discover",
      fi: "Piilota etusivun ehdotukset – löydä",
      fr: "Masquer les suggestions de page d'accueil - Découvrir",
      de: "Vorschläge für die Startseite ausblenden – Entdecken",
      el: "Απόκρυψη προτάσεων αρχικής σελίδας - Discover",
      he: "הסתר הצעות לדף הבית - גלה",
      hi: "मुख पृष्ठ सुझाव छिपाएँ - खोजें",
      hu: "Kezdőlapjavaslatok elrejtése – Fedezze fel",
      id: "Sembunyikan Saran Halaman Beranda - Temukan",
      it: "Nascondi suggerimenti sulla home page - Scopri",
      ja: "ホームページの提案を非表示にする - 発見",
      ko: "홈 페이지 제안 숨기기 - 검색",
      ms: "Sembunyikan Cadangan Halaman Utama - Temui",
      no: "Skjul forslag til startside – Oppdag",
      pl: "Ukryj sugestie strony głównej - Odkryj",
      pt: "Ocultar sugestões da página inicial - Descobrir",
      ro: "Ascundeți sugestiile paginii de pornire - Descoperiți",
      ru: "Скрыть предложения на главной странице — Откройте для себя",
      sk: "Skryť návrhy domovskej stránky – objavte",
      es: "Ocultar sugerencias de página de inicio - Descubrir",
      sv: "Dölj förslag på startsida - Upptäck",
      th: "ซ่อนคำแนะนำหน้าแรก - ค้นหา",
      tr: "Ana Sayfa Önerilerini Gizle - Keşfet",
      uk: "Приховати пропозиції домашньої сторінки - Відкрийте",
      vi: "Ẩn gợi ý trang chủ - Khám phá",
    },
    id: "socialFocus_blueSky_feed_hide_discover_section",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء اقتراحات الصفحة الرئيسية - المتابعة",
      ca: "Amaga els suggeriments de la pàgina d'inici - Seguint",
      "zh-CN": "隐藏主页建议 - 关注",
      "zh-TW": "隱藏主頁建議 - 關注",
      hr: "Sakrij prijedloge početne stranice - Praćenje",
      cs: "Skrýt návrhy domovské stránky – sledování",
      da: "Skjul forslag til startside - Følger",
      nl: "Suggesties voor startpagina verbergen - Volgend",
      en: "Hide Home Page Suggestions - Following",
      fi: "Piilota etusivun ehdotukset - Seurataan",
      fr: "Masquer les suggestions de la page d'accueil - Suivant",
      de: "Vorschläge für die Startseite ausblenden – Folgen",
      el: "Απόκρυψη Προτάσεων Αρχικής Σελίδας - Ακολουθούν",
      he: "הסתר הצעות לדף הבית - עוקב",
      hi: "होम पेज छिपाएँ सुझाव - अनुसरण कर रहे हैं",
      hu: "Kezdőlapjavaslatok elrejtése – Követve",
      id: "Sembunyikan Saran Halaman Beranda - Mengikuti",
      it: "Nascondi suggerimenti sulla home page - Seguito",
      ja: "ホームページの提案を非表示にする - フォロー中",
      ko: "홈 페이지 제안 숨기기 - 팔로잉",
      ms: "Sembunyikan Cadangan Halaman Utama - Mengikuti",
      no: "Skjul forslag til startside - Følger",
      pl: "Ukryj sugestie strony głównej - Obserwowanie",
      pt: "Ocultar sugestões da página inicial - Seguindo",
      ro: "Ascundeți sugestiile paginii de pornire - Urmăriți",
      ru: "Скрыть предложения на главной странице – подписка",
      sk: "Skryť návrhy domovskej stránky – sledovanie",
      es: "Ocultar sugerencias de página de inicio: siguientes",
      sv: "Dölj förslag på startsida - Följer",
      th: "ซ่อนคำแนะนำหน้าแรก - การติดตาม",
      tr: "Ana Sayfa Önerilerini Gizle - Takip Ediliyor",
      uk: "Приховати пропозиції домашньої сторінки - стежити",
      vi: "Ẩn đề xuất trang chủ - Đang theo dõi",
    },
    id: "socialFocus_blueSky_feed_hide_home_following",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء إعدادات خلاصة الصفحة الرئيسية",
      ca: "Amaga la configuració del feed de la pàgina d'inici",
      "zh-CN": "隐藏主页提要设置",
      "zh-TW": "隱藏主頁提要設置",
      hr: "Sakrij postavke feeda početne stranice",
      cs: "Skrýt nastavení zdroje domovské stránky",
      da: "Skjul indstillinger for startsidefeed",
      nl: "Feedinstellingen voor startpagina verbergen",
      en: "Hide Home Page Feed Settings",
      fi: "Piilota kotisivun syötteen asetukset",
      fr: "Masquer les paramètres de flux de la page d'accueil",
      de: "Startseiten-Feed-Einstellungen ausblenden",
      el: "Απόκρυψη ρυθμίσεων ροής αρχικής σελίδας",
      he: "הסתר את הגדרות העדכון של דף הבית",
      hi: "होम पेज फ़ीड सेटिंग्स छिपाएँ",
      hu: "Kezdőlap-hírcsatorna-beállítások elrejtése",
      id: "Sembunyikan Pengaturan Umpan Halaman Beranda",
      it: "Nascondi le impostazioni del feed della home page",
      ja: "ホームページのフィード設定を非表示にする",
      ko: "홈 페이지 피드 설정 숨기기",
      ms: "Sembunyikan Tetapan Suapan Halaman Utama",
      no: "Skjul innmatingsinnstillinger for hjemmesiden",
      pl: "Ukryj ustawienia kanału strony głównej",
      pt: "Ocultar configurações de feed da página inicial",
      ro: "Ascundeți setările pentru fluxul paginii de pornire",
      ru: "Скрыть настройки ленты главной страницы",
      sk: "Skryť nastavenia informačného kanála domovskej stránky",
      es: "Ocultar la configuración del feed de la página de inicio",
      sv: "Dölj flödesinställningar för startsidan",
      th: "ซ่อนการตั้งค่าฟีดหน้าแรก",
      tr: "Ana Sayfa Özet Akışı Ayarlarını Gizle",
      uk: "Приховати налаштування каналу домашньої сторінки",
      vi: "Ẩn cài đặt nguồn cấp dữ liệu trang chủ",
    },
    id: "socialFocus_blueSky_feed_hide_feed_settings",
    defaultValue: false,
  },
];

const blueSkyDesktopGroups_Post = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء صور الملف الشخصي للنشر",
      ca: "Amaga les imatges de perfil de la publicació",
      "zh-CN": "隐藏帖子个人资料图片",
      "zh-TW": "隱藏貼文個人資料圖片",
      hr: "Sakrij objavu profilnih slika",
      cs: "Skrýt profilové obrázky příspěvků",
      da: "Skjul indlægsprofilbilleder",
      nl: "Verberg berichtprofielfoto's",
      en: "Hide Post Profile Pictures",
      fi: "Piilota viestien profiilikuvat",
      fr: "Masquer les photos de profil de publication",
      de: "Beitragsprofilbilder ausblenden",
      el: "Απόκρυψη φωτογραφιών προφίλ ανάρτησης",
      he: "הסתר תמונות פרופיל פוסטים",
      hi: "पोस्ट प्रोफ़ाइल चित्र छिपाएँ",
      hu: "Bejegyzés profilképeinek elrejtése",
      id: "Sembunyikan Gambar Profil Posting",
      it: "Nascondi le immagini del profilo dei post",
      ja: "投稿のプロフィール写真を非表示にする",
      ko: "게시물 프로필 사진 숨기기",
      ms: "Sembunyikan Gambar Profil Siaran",
      no: "Skjul innlegg profilbilder",
      pl: "Ukryj publikuj zdjęcia profilowe",
      pt: "Ocultar fotos de perfil de postagem",
      ro: "Ascundeți fotografiile de profil postare",
      ru: "Скрыть изображения профиля публикации",
      sk: "Skryť profilové obrázky príspevkov",
      es: "Ocultar imágenes de perfil de publicación",
      sv: "Dölj inläggsprofilbilder",
      th: "ซ่อนรูปภาพโปรไฟล์โพสต์",
      tr: "Gönderi Profil Resimlerini Gizle",
      uk: "Приховати фотографії профілю публікації",
      vi: "Ẩn bài đăng Ảnh hồ sơ",
    },
    id: "socialFocus_blueSky_hide_post_profile_pictures",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء صور المشاركات",
      ca: "Amaga imatges de publicacions",
      "zh-CN": "隐藏帖子图片",
      "zh-TW": "隱藏貼文圖片",
      hr: "Sakrij slike objava",
      cs: "Skrýt obrázky příspěvků",
      da: "Skjul indlægsbilleder",
      nl: "Afbeeldingen van berichten verbergen",
      en: "Hide Posts Images",
      fi: "Piilota viestien kuvat",
      fr: "Masquer les images des messages",
      de: "Beitragsbilder ausblenden",
      el: "Απόκρυψη εικόνων αναρτήσεων",
      he: "הסתר תמונות פוסטים",
      hi: "पोस्ट छवियाँ छिपाएँ",
      hu: "Hozzászólások képeinek elrejtése",
      id: "Sembunyikan Gambar Postingan",
      it: "Nascondi le immagini dei post",
      ja: "投稿画像を非表示にする",
      ko: "게시물 이미지 숨기기",
      ms: "Sembunyikan Imej Siaran",
      no: "Skjul innleggsbilder",
      pl: "Ukryj obrazy postów",
      pt: "Ocultar imagens de postagens",
      ro: "Ascunde postări Imagini",
      ru: "Скрыть изображения сообщений",
      sk: "Skryť obrázky príspevkov",
      es: "Ocultar imágenes de publicaciones",
      sv: "Dölj inläggsbilder",
      th: "ซ่อนรูปภาพโพสต์",
      tr: "Gönderi Görsellerini Gizle",
      uk: "Приховати зображення публікацій",
      vi: "Ẩn bài viết Hình ảnh",
    },
    id: "socialFocus_blueSky_hide_post_images",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء مشاركات الفيديو",
      ca: "Amaga els vídeos de publicacions",
      "zh-CN": "隐藏帖子视频",
      "zh-TW": "隱藏帖子視頻",
      hr: "Sakrij objave Videozapisi",
      cs: "Skrýt příspěvky videa",
      da: "Skjul indlægsvideoer",
      nl: "Berichten verbergen Video's",
      en: "Hide Posts Videos",
      fi: "Piilota viestien videot",
      fr: "Masquer les messages Vidéos",
      de: "Beitragsvideos ausblenden",
      el: "Απόκρυψη βίντεο αναρτήσεων",
      he: "הסתר סרטוני פוסטים",
      hi: "पोस्ट वीडियो छिपाएँ",
      hu: "Hozzászólások elrejtése Videók",
      id: "Sembunyikan Postingan Video",
      it: "Nascondi i video dei post",
      ja: "投稿ビデオを非表示にする",
      ko: "게시물 동영상 숨기기",
      ms: "Sembunyikan Siaran Video",
      no: "Skjul innleggsvideoer",
      pl: "Ukryj posty wideo",
      pt: "Ocultar postagens de vídeos",
      ro: "Ascunde postări video",
      ru: "Скрыть видео сообщений",
      sk: "Skryť príspevky Videá",
      es: "Ocultar publicaciones Vídeos",
      sv: "Dölj inläggsvideor",
      th: "ซ่อนวิดีโอโพสต์",
      tr: "Gönderi Videolarını Gizle",
      uk: "Приховати дописи Відео",
      vi: "Ẩn bài viết Video",
    },
    id: "socialFocus_blueSky_hide_post_videos",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء أزرار النشر السفلية",
      ca: "Amaga els botons de la part inferior de la publicació",
      "zh-CN": "隐藏帖子底部按钮",
      "zh-TW": "隱藏貼文底部按鈕",
      hr: "Sakrij gumbe na dnu postolja",
      cs: "Skrýt tlačítka na spodní straně příspěvku",
      da: "Skjul knapper i bunden af ​​indlægget",
      nl: "Knoppen onderste bericht verbergen",
      en: "Hide Post Bottom Buttons",
      fi: "Piilota viestien alapainikkeet",
      fr: "Masquer les boutons du bas de la publication",
      de: "Post-Bottom-Schaltflächen ausblenden",
      el: "Απόκρυψη κουμπιών στο κάτω μέρος της ανάρτησης",
      he: "הסתר כפתורי פוסט תחתונים",
      hi: "पोस्ट के निचले बटन छिपाएँ",
      hu: "A bejegyzés alsó gombjainak elrejtése",
      id: "Sembunyikan Tombol Bawah Posting",
      it: "Nascondi i pulsanti in fondo al post",
      ja: "投稿の下部ボタンを非表示にする",
      ko: "게시물 하단 버튼 숨기기",
      ms: "Sembunyikan Butang Siar Bawah",
      no: "Skjul knappene for innlegg nederst",
      pl: "Ukryj dolne przyciski słupka",
      pt: "Ocultar botões inferiores da postagem",
      ro: "Ascunde butoanele de jos postare",
      ru: "Скрыть кнопки внизу публикации",
      sk: "Skryť tlačidlá na dne príspevku",
      es: "Ocultar botones inferiores de publicación",
      sv: "Dölj knappar under posten",
      th: "ซ่อนปุ่มโพสต์ด้านล่าง",
      tr: "Gönderinin Alt Butonlarını Gizle",
      uk: "Приховати нижні кнопки публікації",
      vi: "Ẩn nút dưới cùng của bài đăng",
    },
    id: "socialFocus_blueSky_hide_post_bottom_buttons",
    defaultValue: false,
  },
];

const blueSkyDesktopGroups_NavigationBar = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الصفحة الرئيسية'",
      ca: "Amaga el botó 'Inici'",
      "zh-CN": "隐藏“主页”按钮",
      "zh-TW": "隱藏「首頁」按鈕",
      hr: "Sakrij gumb 'Početna'",
      cs: "Skrýt tlačítko „Domů“",
      da: "Skjul 'Hjem'-knap",
      nl: "Verberg de 'Home'-knop",
      en: "Hide 'Home' Button",
      fi: "Piilota Koti-painike",
      fr: "Masquer le bouton « Accueil »",
      de: "„Home“-Schaltfläche ausblenden",
      el: "Απόκρυψη κουμπιού 'Αρχική σελίδα'",
      he: "הסתר את כפתור 'בית'",
      hi: "'होम' बटन छिपाएँ",
      hu: "A „Kezdőlap” gomb elrejtése",
      id: "Sembunyikan Tombol 'Beranda'",
      it: "Nascondi il pulsante 'Home'",
      ja: "「ホーム」ボタンを隠す",
      ko: "'홈' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Home'",
      no: "Skjul 'Hjem'-knappen",
      pl: "Ukryj przycisk „Strona główna”",
      pt: "Ocultar o botão 'Home'",
      ro: "Ascundeți butonul „Acasă”",
      ru: "Скрыть кнопку «Домой»",
      sk: "Skryť tlačidlo „Domov“",
      es: "Ocultar el botón 'Inicio'",
      sv: "Dölj 'Hem'-knappen",
      th: "ซ่อนปุ่ม 'หน้าแรก'",
      tr: "'Ana Sayfa' Düğmesini Gizle",
      uk: "Сховати кнопку «Додому»",
      vi: "Ẩn nút 'Trang chủ'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_home",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'البحث'",
      ca: "Amaga el botó 'Cerca'",
      "zh-CN": "隐藏“搜索”按钮",
      "zh-TW": "隱藏“搜尋”按鈕",
      hr: "Sakrij gumb 'Traži'",
      cs: "Skrýt tlačítko „Hledat“",
      da: "Skjul knappen 'Søg'",
      nl: "Knop 'Zoeken' verbergen",
      en: "Hide 'Search' Button",
      fi: "Piilota 'Haku' -painike",
      fr: "Masquer le bouton « Rechercher »",
      de: "Schaltfläche „Suchen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Αναζήτηση»",
      he: "הסתר את לחצן 'חיפוש'",
      hi: "'खोज' बटन छिपाएँ",
      hu: "A „Keresés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Cari'",
      it: "Nascondi il pulsante 'Cerca'",
      ja: "「検索」ボタンを非表示にする",
      ko: "'검색' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Cari'",
      no: "Skjul 'Søk'-knappen",
      pl: "Ukryj przycisk „Szukaj”",
      pt: "Ocultar botão 'Pesquisar'",
      ro: "Ascundeți butonul „Căutare”",
      ru: "Скрыть кнопку «Поиск»",
      sk: "Skryť tlačidlo „Hľadať“",
      es: "Ocultar el botón 'Buscar'",
      sv: "Dölj 'Sök'-knappen",
      th: "ซ่อนปุ่ม 'ค้นหา'",
      tr: "'Ara' Düğmesini Gizle",
      uk: "Сховати кнопку «Пошук»",
      vi: "Ẩn nút 'Tìm kiếm'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_search",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الإخطارات'",
      ca: "Amaga el botó 'Notificacions'",
      "zh-CN": "隐藏“通知”按钮",
      "zh-TW": "隱藏「通知」按鈕",
      hr: "Sakrij gumb 'Obavijesti'",
      cs: "Skrýt tlačítko 'Oznámení'",
      da: "Skjul knappen 'Meddelelser'",
      nl: "Knop 'Meldingen' verbergen",
      en: "Hide 'Notifications' Button",
      fi: "Piilota Ilmoitukset-painike",
      fr: "Masquer le bouton « Notifications »",
      de: "Schaltfläche „Benachrichtigungen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ειδοποιήσεις»",
      he: "הסתר את לחצן 'התראות'",
      hi: "'सूचनाएँ' बटन छिपाएँ",
      hu: "Az „Értesítések” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pemberitahuan'",
      it: "Nascondi il pulsante 'Notifiche'",
      ja: "「通知」ボタンを非表示にする",
      ko: "'알림' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Pemberitahuan'",
      no: "Skjul 'Varslinger'-knappen",
      pl: "Ukryj przycisk „Powiadomienia”",
      pt: "Ocultar botão 'Notificações'",
      ro: "Ascundeți butonul „Notificări”",
      ru: "Скрыть кнопку «Уведомления»",
      sk: "Skryť tlačidlo „Upozornenia“",
      es: "Ocultar el botón 'Notificaciones'",
      sv: "Dölj knappen 'Meddelanden'",
      th: "ซ่อนปุ่ม 'การแจ้งเตือน'",
      tr: "'Bildirimler' Düğmesini Gizle",
      uk: "Сховати кнопку «Сповіщення»",
      vi: "Ẩn nút 'Thông báo'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_notifications",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الدردشة'",
      ca: "Amaga el botó 'Xat'",
      "zh-CN": "隐藏“聊天”按钮",
      "zh-TW": "隱藏“聊天”按鈕",
      hr: "Sakrij gumb 'Chat'",
      cs: "Skrýt tlačítko „Chat“",
      da: "Skjul 'Chat'-knap",
      nl: "Knop 'Chat' verbergen",
      en: "Hide 'Chat' Button",
      fi: "Piilota Chat-painike",
      fr: "Masquer le bouton « Chat »",
      de: "Schaltfläche „Chat“ ausblenden",
      el: "Απόκρυψη κουμπιού «Συζήτηση»",
      he: "הסתר את לחצן 'צ'אט'",
      hi: "'चैट' बटन छिपाएँ",
      hu: "A „Csevegés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Obrolan'",
      it: "Nascondi il pulsante 'Chat'",
      ja: "「チャット」ボタンを非表示にする",
      ko: "'채팅' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Sembang'",
      no: "Skjul 'Chat'-knappen",
      pl: "Ukryj przycisk „Czat”",
      pt: "Ocultar botão 'Bate-papo'",
      ro: "Ascundeți butonul „Chat”",
      ru: "Скрыть кнопку «Чат»",
      sk: "Skryť tlačidlo „Rozhovor“",
      es: "Ocultar el botón 'Chat'",
      sv: "Dölj 'Chatt'-knappen",
      th: "ซ่อนปุ่ม 'แชท'",
      tr: "'Sohbet' Düğmesini Gizle",
      uk: "Сховати кнопку «Чат»",
      vi: "Ẩn nút 'Trò chuyện'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_chat",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الخلاصات'",
      ca: "Amaga el botó 'Feeds'",
      "zh-CN": "隐藏“提要”按钮",
      "zh-TW": "隱藏「提要」按鈕",
      hr: "Sakrij gumb 'Feeds'",
      cs: "Skrýt tlačítko 'Fedy'",
      da: "Skjul 'Feeds'-knap",
      nl: "Knop 'Feeds' verbergen",
      en: "Hide 'Feeds' Button",
      fi: "Piilota 'Syötteet'-painike",
      fr: "Masquer le bouton « Flux »",
      de: "Schaltfläche „Feeds“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Ροές'",
      he: "הסתר כפתור 'הזנות'",
      hi: "'फ़ीड्स' बटन छिपाएँ",
      hu: "A „Hírcsatornák” gomb elrejtése",
      id: "Sembunyikan Tombol 'Umpan'",
      it: "Nascondi il pulsante 'Feed'",
      ja: "「フィード」ボタンを非表示にする",
      ko: "'피드' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Suapan'",
      no: "Skjul 'Feeds'-knappen",
      pl: "Ukryj przycisk „Kanały”",
      pt: "Ocultar botão 'Feeds'",
      ro: "Ascundeți butonul „Feeduri”",
      ru: "Скрыть кнопку «Ленты»",
      sk: "Skryť tlačidlo „Informačné kanály“",
      es: "Ocultar el botón 'Feeds'",
      sv: "Dölj 'Feeds'-knappen",
      th: "ซ่อนปุ่ม 'ฟีด'",
      tr: "'Yayınlar' Düğmesini Gizle",
      uk: "Сховати кнопку «Канали»",
      vi: "Ẩn nút 'Nguồn cấp dữ liệu'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_feeds",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'القوائم'",
      ca: "Amaga el botó 'Llistes'",
      "zh-CN": "隐藏“列表”按钮",
      "zh-TW": "隱藏“清單”按鈕",
      hr: "Sakrij gumb 'Popisi'",
      cs: "Skrýt tlačítko „Seznamy“",
      da: "Skjul 'Lister'-knap",
      nl: "Knop 'Lijsten' verbergen",
      en: "Hide 'Lists' Button",
      fi: "Piilota Listat-painike",
      fr: "Masquer le bouton « Listes »",
      de: "Schaltfläche „Listen“ ausblenden",
      el: "Κουμπί απόκρυψης 'Λίστες'",
      he: "הסתר כפתור 'רשימות'",
      hi: "'सूचियाँ' बटन छिपाएँ",
      hu: "A „Listák” gomb elrejtése",
      id: "Sembunyikan Tombol 'Daftar'",
      it: "Nascondi il pulsante 'Elenchi'",
      ja: "「リスト」ボタンを非表示にする",
      ko: "'목록' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Senarai'",
      no: "Skjul 'Lister'-knappen",
      pl: "Ukryj przycisk „Listy”",
      pt: "Ocultar botão 'Listas'",
      ro: "Ascundeți butonul „Liste”",
      ru: "Скрыть кнопку «Списки»",
      sk: "Skryť tlačidlo „Zoznamy“",
      es: "Ocultar el botón 'Listas'",
      sv: "Dölj knappen 'Lists'",
      th: "ซ่อนปุ่ม 'รายการ'",
      tr: "'Listeler' Düğmesini Gizle",
      uk: "Приховати кнопку «Списки»",
      vi: "Ẩn nút 'Danh sách'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_lists",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الملف الشخصي'",
      ca: "Amaga el botó 'Perfil'",
      "zh-CN": "隐藏“个人资料”按钮",
      "zh-TW": "隱藏「個人資料」按鈕",
      hr: "Sakrij gumb 'Profil'",
      cs: "Skrýt tlačítko „Profil“",
      da: "Skjul 'Profil'-knap",
      nl: "Knop 'Profiel' verbergen",
      en: "Hide 'Profile' Button",
      fi: "Piilota 'Profiili'-painike",
      fr: "Masquer le bouton « Profil »",
      de: "Schaltfläche „Profil“ ausblenden",
      el: "Κουμπί απόκρυψης 'Προφίλ'",
      he: "הסתר כפתור 'פרופיל'",
      hi: "'प्रोफ़ाइल' बटन छिपाएँ",
      hu: "A „Profil” gomb elrejtése",
      id: "Sembunyikan Tombol 'Profil'",
      it: "Nascondi il pulsante 'Profilo'",
      ja: "「プロフィール」ボタンを非表示にする",
      ko: "'프로필' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Profil'",
      no: "Skjul 'Profil'-knappen",
      pl: "Ukryj przycisk „Profil”",
      pt: "Ocultar botão 'Perfil'",
      ro: "Ascunde butonul „Profil”",
      ru: "Скрыть кнопку «Профиль»",
      sk: "Skryť tlačidlo „Profil“",
      es: "Ocultar botón 'Perfil'",
      sv: "Dölj 'Profil'-knappen",
      th: "ซ่อนปุ่ม 'โปรไฟล์'",
      tr: "'Profil' Düğmesini Gizle",
      uk: "Приховати кнопку «Профіль»",
      vi: "Ẩn nút 'Hồ sơ'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_profile",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الإعدادات'",
      ca: "Amaga el botó 'Configuració'",
      "zh-CN": "隐藏“设置”按钮",
      "zh-TW": "隱藏“設定”按鈕",
      hr: "Sakrij gumb 'Postavke'",
      cs: "Skrýt tlačítko „Nastavení“",
      da: "Skjul knappen 'Indstillinger'",
      nl: "Knop 'Instellingen' verbergen",
      en: "Hide 'Settings' Button",
      fi: "Piilota Asetukset-painike",
      fr: "Masquer le bouton « Paramètres »",
      de: "Schaltfläche „Einstellungen“ ausblenden",
      el: "Απόκρυψη του κουμπιού 'Ρυθμίσεις'",
      he: "הסתר את לחצן 'הגדרות'",
      hi: "'सेटिंग्स' बटन छिपाएँ",
      hu: "A „Beállítások” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pengaturan'",
      it: "Nascondi il pulsante 'Impostazioni'",
      ja: "「設定」ボタンを非表示にする",
      ko: "'설정' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Tetapan'",
      no: "Skjul 'Innstillinger'-knappen",
      pl: "Ukryj przycisk „Ustawienia”",
      pt: "Ocultar botão 'Configurações'",
      ro: "Ascundeți butonul „Setări”",
      ru: "Скрыть кнопку «Настройки»",
      sk: "Skryť tlačidlo „Nastavenia“",
      es: "Ocultar el botón 'Configuración'",
      sv: "Dölj knappen 'Inställningar'",
      th: "ซ่อนปุ่ม 'การตั้งค่า'",
      tr: "'Ayarlar' Düğmesini Gizle",
      uk: "Сховати кнопку «Налаштування»",
      vi: "Ẩn nút 'Cài đặt'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_settings",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'نشر جديد'",
      ca: "Amaga el botó 'Publicació nova'",
      "zh-CN": "隐藏“新帖子”按钮",
      "zh-TW": "隱藏「新貼文」按鈕",
      hr: "Sakrij gumb 'Novi post'",
      cs: "Skrýt tlačítko 'Nový příspěvek'",
      da: "Skjul knappen 'Nyt indlæg'",
      nl: "Knop 'Nieuw bericht' verbergen",
      en: "Hide 'New Post' Button",
      fi: "Piilota Uusi viesti -painike",
      fr: "Masquer le bouton « Nouveau message »",
      de: "Schaltfläche „Neuer Beitrag“ ausblenden",
      el: "Απόκρυψη του κουμπιού 'Νέα ανάρτηση'",
      he: "הסתר את לחצן 'פוסט חדש'",
      hi: "'नया पोस्ट' बटन छिपाएँ",
      hu: "Az „Új bejegyzés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Postingan Baru'",
      it: "Nascondi il pulsante 'Nuovo post'",
      ja: "「新規投稿」ボタンを非表示にする",
      ko: "'새 게시물' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Siaran Baharu'",
      no: "Skjul 'Nytt innlegg'-knappen",
      pl: "Ukryj przycisk „Nowy post”",
      pt: "Ocultar o botão ‘Nova postagem’",
      ro: "Ascundeți butonul „Postare nouă”",
      ru: "Скрыть кнопку «Новое сообщение»",
      sk: "Skryť tlačidlo „Nový príspevok“",
      es: "Ocultar el botón 'Nueva publicación'",
      sv: "Dölj knappen 'Nytt inlägg'",
      th: "ซ่อนปุ่ม 'โพสต์ใหม่'",
      tr: "'Yeni Gönderi' Düğmesini Gizle",
      uk: "Приховати кнопку «Нова публікація»",
      vi: "Ẩn nút 'Bài đăng mới'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_new_post",
    defaultValue: false,
  },
];

const blueSkyDesktopGroups_RightBar = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء البحث",
      ca: "Amaga la cerca",
      "zh-CN": "隐藏搜索",
      "zh-TW": "隱藏搜尋",
      hr: "Sakrij pretraživanje",
      cs: "Skrýt vyhledávání",
      da: "Skjul søgning",
      nl: "Zoekopdracht verbergen",
      en: "Hide Search",
      fi: "Piilota haku",
      fr: "Masquer la recherche",
      de: "Suche ausblenden",
      el: "Απόκρυψη αναζήτησης",
      he: "הסתר את החיפוש",
      hi: "खोज छिपाएँ",
      hu: "Keresés elrejtése",
      id: "Sembunyikan Pencarian",
      it: "Nascondi ricerca",
      ja: "検索を非表示にする",
      ko: "검색 숨기기",
      ms: "Sembunyikan Carian",
      no: "Skjul søk",
      pl: "Ukryj wyszukiwanie",
      pt: "Ocultar pesquisa",
      ro: "Ascunde căutarea",
      ru: "Скрыть поиск",
      sk: "Skryť vyhľadávanie",
      es: "Ocultar búsqueda",
      sv: "Dölj sökning",
      th: "ซ่อนการค้นหา",
      tr: "Aramayı Gizle",
      uk: "Приховати пошук",
      vi: "Ẩn tìm kiếm",
    },
    id: "socialFocus_blueSky_rightBar_hide_search",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم البدء",
      ca: "Amaga la secció Introducció",
      "zh-CN": "隐藏入门部分",
      "zh-TW": "隱藏入門部分",
      hr: "Sakrij odjeljak Prvi koraci",
      cs: "Skrýt sekci Začínáme",
      da: "Skjul afsnittet Kom godt i gang",
      nl: "Sectie 'Aan de slag' verbergen",
      en: "Hide Getting Started Section",
      fi: "Piilota Aloitusosio",
      fr: "Masquer la section Mise en route",
      de: "Abschnitt „Erste Schritte“ ausblenden",
      el: "Απόκρυψη ενότητας Ξεκινώντας",
      he: "הסתר את סעיף תחילת העבודה",
      hi: "प्रारंभ करना अनुभाग छिपाएँ",
      hu: "Az Első lépések szakasz elrejtése",
      id: "Sembunyikan Bagian Memulai",
      it: "Nascondi la sezione Per iniziare",
      ja: "「はじめに」セクションを非表示にする",
      ko: "시작하기 섹션 숨기기",
      ms: "Sembunyikan Bahagian Bermula",
      no: "Skjul Komme i gang-delen",
      pl: "Ukryj sekcję Pierwsze kroki",
      pt: "Ocultar seção de primeiros passos",
      ro: "Ascundeți secțiunea Introducere",
      ru: "Скрыть раздел «Начало работы»",
      sk: "Skryť sekciu Začíname",
      es: "Ocultar sección de introducción",
      sv: "Dölj avsnittet Komma igång",
      th: "ซ่อนส่วนการเริ่มต้นใช้งาน",
      tr: "Başlarken Bölümünü Gizle",
      uk: "Приховати розділ «Початок роботи»",
      vi: "Ẩn phần Bắt đầu",
    },
    id: "socialFocus_blueSky_rightBar_hide_getting_started_section",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء تذييل الشريط الأيمن",
      ca: "Amaga el peu de pàgina de la barra dreta",
      "zh-CN": "隐藏右栏页脚",
      "zh-TW": "隱藏右欄頁腳",
      hr: "Sakrij podnožje desne trake",
      cs: "Skrýt zápatí pravého pruhu",
      da: "Skjul højre sidefod",
      nl: "Rechterbalkvoettekst verbergen",
      en: "Hide Right Bar Footer",
      fi: "Piilota oikean palkin alatunniste",
      fr: "Masquer le pied de page de la barre droite",
      de: "Rechte Fußzeile ausblenden",
      el: "Απόκρυψη υποσέλιδου δεξιάς γραμμής",
      he: "הסתר כותרת תחתונה של סרגל ימין",
      hi: "दायाँ बार फ़ुटर छिपाएँ",
      hu: "A jobb oldali sáv láblécének elrejtése",
      id: "Sembunyikan Footer Bar Kanan",
      it: "Nascondi piè di pagina della barra destra",
      ja: "右バーのフッターを非表示にする",
      ko: "오른쪽 막대 바닥글 숨기기",
      ms: "Sembunyikan Pengaki Bar Kanan",
      no: "Skjul bunntekst på høyre stolpe",
      pl: "Ukryj prawą stopkę paska",
      pt: "Ocultar rodapé da barra direita",
      ro: "Ascunde subsolul barei din dreapta",
      ru: "Скрыть нижний колонтитул правой панели",
      sk: "Skryť pätu pravej lišty",
      es: "Ocultar pie de página de la barra derecha",
      sv: "Dölj höger fältfot",
      th: "ซ่อนส่วนท้ายของแถบด้านขวา",
      tr: "Sağ Çubuk Alt Bilgisini Gizle",
      uk: "Приховати нижній колонтитул правої панелі",
      vi: "Ẩn chân trang bên phải",
    },
    id: "socialFocus_blueSky_rightBar_hide_footer",
    defaultValue: false,
  },
];

// MARK: - Desktop Builder

const blueSkyDesktopGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "blueSky",
    options: [blueSkyDesktopGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "blueSky",
    options: blueSkyDesktopGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "blueSky",
    options: blueSkyDesktopGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "الصفحة الرئيسية",
      ca: "Pàgina d'inici",
      "zh-CN": "主页",
      "zh-TW": "首頁",
      hr: "Početna stranica",
      cs: "Domovská stránka",
      da: "Hjemmeside",
      nl: "Startpagina",
      en: "Home Page",
      fi: "Kotisivu",
      fr: "Page d'accueil",
      de: "Startseite",
      el: "Αρχική Σελίδα",
      he: "דף הבית",
      hi: "होम पेज",
      hu: "Kezdőlap",
      id: "Halaman Beranda",
      it: "Pagina iniziale",
      ja: "ホームページ",
      ko: "홈 페이지",
      ms: "Halaman Utama",
      no: "Hjemmeside",
      pl: "Strona główna",
      pt: "Pagina inicial",
      ro: "Pagina principala",
      ru: "Домашняя страница",
      sk: "Domovská stránka",
      es: "Página de inicio",
      sv: "Hemsida",
      th: "หน้าแรก",
      tr: "Ana Sayfa",
      uk: "Домашня сторінка",
      vi: "Trang chủ",
    },
    groupId: "feed",
    parentCategoryId: "blueSky",
    options: blueSkyDesktopGroups_Feed,
  },
  {
    groupName: {
      ar: "دعامات",
      ca: "Publicacions",
      "zh-CN": "帖子",
      "zh-TW": "貼文",
      hr: "Postovi",
      cs: "Příspěvky",
      da: "Indlæg",
      nl: "Berichten",
      en: "Posts",
      fi: "Viestit",
      fr: "Des postes",
      de: "Beiträge",
      el: "Αναρτήσεις",
      he: "פוסטים",
      hi: "पदों",
      hu: "Hozzászólások",
      id: "Postingan",
      it: "Messaggi",
      ja: "投稿",
      ko: "게시물",
      ms: "Catatan",
      no: "Innlegg",
      pl: "Posty",
      pt: "Postagens",
      ro: "Postări",
      ru: "Сообщения",
      sk: "Príspevky",
      es: "Publicaciones",
      sv: "Inlägg",
      th: "กระทู้",
      tr: "Gönderiler",
      uk: "Пости",
      vi: "Bài viết",
    },
    groupId: "post",
    parentCategoryId: "blueSky",
    options: blueSkyDesktopGroups_Post,
  },
  {
    groupName: {
      ar: "شريط التنقل",
      ca: "Barra de navegació",
      "zh-CN": "导航栏",
      "zh-TW": "導覽列",
      hr: "Navigacijska traka",
      cs: "Navigační lišta",
      da: "Navigations bar",
      nl: "Navigatiebalk",
      en: "Navigation Bar",
      fi: "Navigointipalkki",
      fr: "Barre de navigation",
      de: "Navigationsleiste",
      el: "Μπάρα πλοήγησης",
      he: "סרגל ניווט",
      hi: "नेविगेशन पट्टी",
      hu: "Navigációs sáv",
      id: "Bilah Navigasi",
      it: "Barra di navigazione",
      ja: "ナビゲーションバー",
      ko: "네비게이션 바",
      ms: "Bar navigasi",
      no: "Navigasjonslinje",
      pl: "Pasek nawigacyjny",
      pt: "Barra de navegação",
      ro: "Bară de navigare",
      ru: "Панель навигации",
      sk: "Navigačná lišta",
      es: "Barra de navegación",
      sv: "Navigeringsfält",
      th: "แถบนำทาง",
      tr: "Gezinti çubuğu",
      uk: "Панель навігації",
      vi: "Thanh điều hướng",
    },
    groupId: "navigationBar",
    parentCategoryId: "blueSky",
    options: blueSkyDesktopGroups_NavigationBar,
  },
  {
    groupName: {
      ar: "الشريط الأيمن",
      ca: "Barra dreta",
      "zh-CN": "右栏",
      "zh-TW": "右欄",
      hr: "Desna traka",
      cs: "Pravá lišta",
      da: "Højre bjælke",
      nl: "Rechter balk",
      en: "Right Bar",
      fi: "Oikea baari",
      fr: "Barre de droite",
      de: "Rechte Leiste",
      el: "Δεξιά Μπάρα",
      he: "בר ימין",
      hi: "सही बार",
      hu: "Jobb bár",
      id: "Bilah Kanan",
      it: "Barra destra",
      ja: "右バー",
      ko: "오른쪽 막대",
      ms: "Bar Kanan",
      no: "Høyre stolpe",
      pl: "Prawy pasek",
      pt: "Barra Direita",
      ro: "Bara din dreapta",
      ru: "Правая панель",
      sk: "Pravá lišta",
      es: "Barra derecha",
      sv: "Höger bar",
      th: "แถบขวา",
      tr: "Sağ Çubuk",
      uk: "Права панель",
      vi: "Thanh bên phải",
    },
    groupId: "rightBar",
    parentCategoryId: "blueSky",
    options: blueSkyDesktopGroups_RightBar,
  },
];

// MARK: - Mobile Groups
const blueSkyMobileGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل SocialFocus على Bluesky",
    ca: "Desactiveu SocialFocus a Bluesky",
    "zh-CN": "在 Bluesky 上禁用 SocialFocus",
    "zh-TW": "在 Bluesky 上停用 SocialFocus",
    hr: "Onemogući SocialFocus na Blueskyju",
    cs: "Zakázat SocialFocus na Bluesky",
    da: "Deaktiver SocialFocus på Bluesky",
    nl: "Schakel SocialFocus uit op Bluesky",
    en: "Disable SocialFocus on Bluesky",
    fi: "Poista SocialFocus käytöstä Blueskyssä",
    fr: "Désactiver SocialFocus sur Bluesky",
    de: "Deaktivieren Sie SocialFocus auf Bluesky",
    el: "Απενεργοποιήστε το SocialFocus στο Bluesky",
    he: "השבת את SocialFocus ב-Blusky",
    hi: "ब्लूस्काई पर सोशलफोकस अक्षम करें",
    hu: "A SocialFocus letiltása a Bluesky-n",
    id: "Nonaktifkan Fokus Sosial di Bluesky",
    it: "Disabilita SocialFocus su Bluesky",
    ja: "Bluesky で SocialFocus を無効にする",
    ko: "Bluesky에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada Bluesky",
    no: "Deaktiver SocialFocus på Bluesky",
    pl: "Wyłącz SocialFocus na Bluesky",
    pt: "Desativar SocialFocus no Bluesky",
    ro: "Dezactivați SocialFocus pe Bluesky",
    ru: "Отключить SocialFocus в Bluesky",
    sk: "Zakázať SocialFocus na Bluesky",
    es: "Deshabilitar SocialFocus en Bluesky",
    sv: "Inaktivera SocialFocus på Bluesky",
    th: "ปิดการใช้งาน SocialFocus บน Bluesky",
    tr: "Bluesky'de SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus на Bluesky",
    vi: "Tắt SocialFocus trên Bluesky",
  },
  id: "socialFocus_blueSky_master_toggle",
  defaultValue: false,
};

const blueSkyMobileGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "بلوك بلوسكي",
      ca: "Bloqueja Bluesky",
      "zh-CN": "块蓝天",
      "zh-TW": "塊藍天",
      hr: "Blokiraj Bluesky",
      cs: "Blok Bluesky",
      da: "Bloker Bluesky",
      nl: "Blokkeer Bluesky",
      en: "Block Bluesky",
      fi: "Estä Bluesky",
      fr: "Bloquer le ciel bleu",
      de: "Blockieren Sie Bluesky",
      el: "Μπλοκ Bluesky",
      he: "בלוק בלוסקי",
      hi: "ब्लूस्काई को ब्लॉक करें",
      hu: "Blokkolja Bluesky-t",
      id: "Blokir Bluesky",
      it: "Blocca Bluesky",
      ja: "ブロック・ブルースカイ",
      ko: "블루스카이 차단",
      ms: "Sekat Bluesky",
      no: "Blokker Bluesky",
      pl: "Zablokuj Bluesky",
      pt: "Bloco Céu Azul",
      ro: "Blocați Bluesky",
      ru: "Блок Блюскай",
      sk: "Block Bluesky",
      es: "Bloquear cielo azul",
      sv: "Block Bluesky",
      th: "บล๊อกบลูสกาย",
      tr: "Bluesky'yi engelle",
      uk: "Блок Bluesky",
      vi: "Chặn Bluesky",
    },
    id: "socialFocus_blueSky_block_blueSky",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_blueSky_gray_mode",
    defaultValue: false,
  },
];

const blueSkyMobileGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_blueSky_daily_limit_show_timer",
    defaultValue: false,
  },
];

const blueSkyMobileGroups_Feed = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء اقتراحات الصفحة الرئيسية - اكتشف",
      ca: "Amaga els suggeriments de la pàgina d'inici - Descobreix",
      "zh-CN": "隐藏主页建议 - 发现",
      "zh-TW": "隱藏主頁建議 - 發現",
      hr: "Sakrij prijedloge početne stranice - Otkrijte",
      cs: "Skrýt návrhy domovské stránky – objevte",
      da: "Skjul forslag til startside - Opdag",
      nl: "Suggesties voor startpagina verbergen - Ontdek",
      en: "Hide Home Page Suggestions - Discover",
      fi: "Piilota etusivun ehdotukset – löydä",
      fr: "Masquer les suggestions de page d'accueil - Découvrir",
      de: "Vorschläge für die Startseite ausblenden – Entdecken",
      el: "Απόκρυψη προτάσεων αρχικής σελίδας - Discover",
      he: "הסתר הצעות לדף הבית - גלה",
      hi: "मुख पृष्ठ सुझाव छिपाएँ - खोजें",
      hu: "Kezdőlapjavaslatok elrejtése – Fedezze fel",
      id: "Sembunyikan Saran Halaman Beranda - Temukan",
      it: "Nascondi suggerimenti sulla home page - Scopri",
      ja: "ホームページの提案を非表示にする - 発見",
      ko: "홈 페이지 제안 숨기기 - 검색",
      ms: "Sembunyikan Cadangan Halaman Utama - Temui",
      no: "Skjul forslag til startside – Oppdag",
      pl: "Ukryj sugestie strony głównej - Odkryj",
      pt: "Ocultar sugestões da página inicial - Descobrir",
      ro: "Ascundeți sugestiile paginii de pornire - Descoperiți",
      ru: "Скрыть предложения на главной странице — Откройте для себя",
      sk: "Skryť návrhy domovskej stránky – objavte",
      es: "Ocultar sugerencias de página de inicio - Descubrir",
      sv: "Dölj förslag på startsida - Upptäck",
      th: "ซ่อนคำแนะนำหน้าแรก - ค้นหา",
      tr: "Ana Sayfa Önerilerini Gizle - Keşfet",
      uk: "Приховати пропозиції домашньої сторінки - Відкрийте",
      vi: "Ẩn gợi ý trang chủ - Khám phá",
    },
    id: "socialFocus_blueSky_feed_hide_discover_section",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء اقتراحات الصفحة الرئيسية - المتابعة",
      ca: "Amaga els suggeriments de la pàgina d'inici - Seguint",
      "zh-CN": "隐藏主页建议 - 关注",
      "zh-TW": "隱藏主頁建議 - 關注",
      hr: "Sakrij prijedloge početne stranice - Praćenje",
      cs: "Skrýt návrhy domovské stránky – sledování",
      da: "Skjul forslag til startside - Følger",
      nl: "Suggesties voor startpagina verbergen - Volgend",
      en: "Hide Home Page Suggestions - Following",
      fi: "Piilota etusivun ehdotukset - Seurataan",
      fr: "Masquer les suggestions de la page d'accueil - Suivant",
      de: "Vorschläge für die Startseite ausblenden – Folgen",
      el: "Απόκρυψη Προτάσεων Αρχικής Σελίδας - Ακολουθούν",
      he: "הסתר הצעות לדף הבית - עוקב",
      hi: "होम पेज छिपाएँ सुझाव - अनुसरण कर रहे हैं",
      hu: "Kezdőlapjavaslatok elrejtése – Követve",
      id: "Sembunyikan Saran Halaman Beranda - Mengikuti",
      it: "Nascondi suggerimenti sulla home page - Seguito",
      ja: "ホームページの提案を非表示にする - フォロー中",
      ko: "홈 페이지 제안 숨기기 - 팔로잉",
      ms: "Sembunyikan Cadangan Halaman Utama - Mengikuti",
      no: "Skjul forslag til startside - Følger",
      pl: "Ukryj sugestie strony głównej - Obserwowanie",
      pt: "Ocultar sugestões da página inicial - Seguindo",
      ro: "Ascundeți sugestiile paginii de pornire - Urmăriți",
      ru: "Скрыть предложения на главной странице – подписка",
      sk: "Skryť návrhy domovskej stránky – sledovanie",
      es: "Ocultar sugerencias de página de inicio: siguientes",
      sv: "Dölj förslag på startsida - Följer",
      th: "ซ่อนคำแนะนำหน้าแรก - การติดตาม",
      tr: "Ana Sayfa Önerilerini Gizle - Takip Ediliyor",
      uk: "Приховати пропозиції домашньої сторінки - стежити",
      vi: "Ẩn đề xuất trang chủ - Đang theo dõi",
    },
    id: "socialFocus_blueSky_feed_hide_home_following",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء إعدادات خلاصة الصفحة الرئيسية",
      ca: "Amaga la configuració del feed de la pàgina d'inici",
      "zh-CN": "隐藏主页提要设置",
      "zh-TW": "隱藏主頁提要設置",
      hr: "Sakrij postavke feeda početne stranice",
      cs: "Skrýt nastavení zdroje domovské stránky",
      da: "Skjul indstillinger for startsidefeed",
      nl: "Feedinstellingen voor startpagina verbergen",
      en: "Hide Home Page Feed Settings",
      fi: "Piilota kotisivun syötteen asetukset",
      fr: "Masquer les paramètres de flux de la page d'accueil",
      de: "Startseiten-Feed-Einstellungen ausblenden",
      el: "Απόκρυψη ρυθμίσεων ροής αρχικής σελίδας",
      he: "הסתר את הגדרות העדכון של דף הבית",
      hi: "होम पेज फ़ीड सेटिंग्स छिपाएँ",
      hu: "Kezdőlap-hírcsatorna-beállítások elrejtése",
      id: "Sembunyikan Pengaturan Umpan Halaman Beranda",
      it: "Nascondi le impostazioni del feed della home page",
      ja: "ホームページのフィード設定を非表示にする",
      ko: "홈 페이지 피드 설정 숨기기",
      ms: "Sembunyikan Tetapan Suapan Halaman Utama",
      no: "Skjul innmatingsinnstillinger for hjemmesiden",
      pl: "Ukryj ustawienia kanału strony głównej",
      pt: "Ocultar configurações de feed da página inicial",
      ro: "Ascundeți setările pentru fluxul paginii de pornire",
      ru: "Скрыть настройки ленты главной страницы",
      sk: "Skryť nastavenia informačného kanála domovskej stránky",
      es: "Ocultar la configuración del feed de la página de inicio",
      sv: "Dölj flödesinställningar för startsidan",
      th: "ซ่อนการตั้งค่าฟีดหน้าแรก",
      tr: "Ana Sayfa Özet Akışı Ayarlarını Gizle",
      uk: "Приховати налаштування каналу домашньої сторінки",
      vi: "Ẩn cài đặt nguồn cấp dữ liệu trang chủ",
    },
    id: "socialFocus_blueSky_feed_hide_feed_settings",
    defaultValue: false,
  },
];

const blueSkyMobileGroups_Post = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء صور الملف الشخصي للنشر",
      ca: "Amaga les imatges de perfil de la publicació",
      "zh-CN": "隐藏帖子个人资料图片",
      "zh-TW": "隱藏貼文個人資料圖片",
      hr: "Sakrij objavu profilnih slika",
      cs: "Skrýt profilové obrázky příspěvků",
      da: "Skjul indlægsprofilbilleder",
      nl: "Verberg berichtprofielfoto's",
      en: "Hide Post Profile Pictures",
      fi: "Piilota viestien profiilikuvat",
      fr: "Masquer les photos de profil de publication",
      de: "Beitragsprofilbilder ausblenden",
      el: "Απόκρυψη φωτογραφιών προφίλ ανάρτησης",
      he: "הסתר תמונות פרופיל פוסטים",
      hi: "पोस्ट प्रोफ़ाइल चित्र छिपाएँ",
      hu: "Bejegyzés profilképeinek elrejtése",
      id: "Sembunyikan Gambar Profil Posting",
      it: "Nascondi le immagini del profilo dei post",
      ja: "投稿のプロフィール写真を非表示にする",
      ko: "게시물 프로필 사진 숨기기",
      ms: "Sembunyikan Gambar Profil Siaran",
      no: "Skjul innlegg profilbilder",
      pl: "Ukryj publikuj zdjęcia profilowe",
      pt: "Ocultar fotos de perfil de postagem",
      ro: "Ascundeți fotografiile de profil postare",
      ru: "Скрыть изображения профиля публикации",
      sk: "Skryť profilové obrázky príspevkov",
      es: "Ocultar imágenes de perfil de publicación",
      sv: "Dölj inläggsprofilbilder",
      th: "ซ่อนรูปภาพโปรไฟล์โพสต์",
      tr: "Gönderi Profil Resimlerini Gizle",
      uk: "Приховати фотографії профілю публікації",
      vi: "Ẩn bài đăng Ảnh hồ sơ",
    },
    id: "socialFocus_blueSky_hide_post_profile_pictures",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء صور المشاركات",
      ca: "Amaga imatges de publicacions",
      "zh-CN": "隐藏帖子图片",
      "zh-TW": "隱藏貼文圖片",
      hr: "Sakrij slike objava",
      cs: "Skrýt obrázky příspěvků",
      da: "Skjul indlægsbilleder",
      nl: "Afbeeldingen van berichten verbergen",
      en: "Hide Posts Images",
      fi: "Piilota viestien kuvat",
      fr: "Masquer les images des messages",
      de: "Beitragsbilder ausblenden",
      el: "Απόκρυψη εικόνων αναρτήσεων",
      he: "הסתר תמונות פוסטים",
      hi: "पोस्ट छवियाँ छिपाएँ",
      hu: "Hozzászólások képeinek elrejtése",
      id: "Sembunyikan Gambar Postingan",
      it: "Nascondi le immagini dei post",
      ja: "投稿画像を非表示にする",
      ko: "게시물 이미지 숨기기",
      ms: "Sembunyikan Imej Siaran",
      no: "Skjul innleggsbilder",
      pl: "Ukryj obrazy postów",
      pt: "Ocultar imagens de postagens",
      ro: "Ascunde postări Imagini",
      ru: "Скрыть изображения сообщений",
      sk: "Skryť obrázky príspevkov",
      es: "Ocultar imágenes de publicaciones",
      sv: "Dölj inläggsbilder",
      th: "ซ่อนรูปภาพโพสต์",
      tr: "Gönderi Görsellerini Gizle",
      uk: "Приховати зображення публікацій",
      vi: "Ẩn bài viết Hình ảnh",
    },
    id: "socialFocus_blueSky_hide_post_images",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء مشاركات الفيديو",
      ca: "Amaga els vídeos de publicacions",
      "zh-CN": "隐藏帖子视频",
      "zh-TW": "隱藏帖子視頻",
      hr: "Sakrij objave Videozapisi",
      cs: "Skrýt příspěvky videa",
      da: "Skjul indlægsvideoer",
      nl: "Berichten verbergen Video's",
      en: "Hide Posts Videos",
      fi: "Piilota viestien videot",
      fr: "Masquer les messages Vidéos",
      de: "Beitragsvideos ausblenden",
      el: "Απόκρυψη βίντεο αναρτήσεων",
      he: "הסתר סרטוני פוסטים",
      hi: "पोस्ट वीडियो छिपाएँ",
      hu: "Hozzászólások elrejtése Videók",
      id: "Sembunyikan Postingan Video",
      it: "Nascondi i video dei post",
      ja: "投稿ビデオを非表示にする",
      ko: "게시물 동영상 숨기기",
      ms: "Sembunyikan Siaran Video",
      no: "Skjul innleggsvideoer",
      pl: "Ukryj posty wideo",
      pt: "Ocultar postagens de vídeos",
      ro: "Ascunde postări video",
      ru: "Скрыть видео сообщений",
      sk: "Skryť príspevky Videá",
      es: "Ocultar publicaciones Vídeos",
      sv: "Dölj inläggsvideor",
      th: "ซ่อนวิดีโอโพสต์",
      tr: "Gönderi Videolarını Gizle",
      uk: "Приховати дописи Відео",
      vi: "Ẩn bài viết Video",
    },
    id: "socialFocus_blueSky_hide_post_videos",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء أزرار النشر السفلية",
      ca: "Amaga els botons de la part inferior de la publicació",
      "zh-CN": "隐藏帖子底部按钮",
      "zh-TW": "隱藏貼文底部按鈕",
      hr: "Sakrij gumbe na dnu postolja",
      cs: "Skrýt tlačítka na spodní straně příspěvku",
      da: "Skjul knapper i bunden af ​​indlægget",
      nl: "Knoppen onderste bericht verbergen",
      en: "Hide Post Bottom Buttons",
      fi: "Piilota viestien alapainikkeet",
      fr: "Masquer les boutons du bas de la publication",
      de: "Post-Bottom-Schaltflächen ausblenden",
      el: "Απόκρυψη κουμπιών στο κάτω μέρος της ανάρτησης",
      he: "הסתר כפתורי פוסט תחתונים",
      hi: "पोस्ट के निचले बटन छिपाएँ",
      hu: "A bejegyzés alsó gombjainak elrejtése",
      id: "Sembunyikan Tombol Bawah Posting",
      it: "Nascondi i pulsanti in fondo al post",
      ja: "投稿の下部ボタンを非表示にする",
      ko: "게시물 하단 버튼 숨기기",
      ms: "Sembunyikan Butang Siar Bawah",
      no: "Skjul knappene for innlegg nederst",
      pl: "Ukryj dolne przyciski słupka",
      pt: "Ocultar botões inferiores da postagem",
      ro: "Ascunde butoanele de jos postare",
      ru: "Скрыть кнопки внизу публикации",
      sk: "Skryť tlačidlá na dne príspevku",
      es: "Ocultar botones inferiores de publicación",
      sv: "Dölj knappar under posten",
      th: "ซ่อนปุ่มโพสต์ด้านล่าง",
      tr: "Gönderinin Alt Butonlarını Gizle",
      uk: "Приховати нижні кнопки публікації",
      vi: "Ẩn nút dưới cùng của bài đăng",
    },
    id: "socialFocus_blueSky_hide_post_bottom_buttons",
    defaultValue: false,
  },
];

const blueSkyMobileGroups_NavigationBar = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الصفحة الرئيسية'",
      ca: "Amaga el botó 'Inici'",
      "zh-CN": "隐藏“主页”按钮",
      "zh-TW": "隱藏「首頁」按鈕",
      hr: "Sakrij gumb 'Početna'",
      cs: "Skrýt tlačítko „Domů“",
      da: "Skjul 'Hjem'-knap",
      nl: "Verberg de 'Home'-knop",
      en: "Hide 'Home' Button",
      fi: "Piilota Koti-painike",
      fr: "Masquer le bouton « Accueil »",
      de: "„Home“-Schaltfläche ausblenden",
      el: "Απόκρυψη κουμπιού 'Αρχική σελίδα'",
      he: "הסתר את כפתור 'בית'",
      hi: "'होम' बटन छिपाएँ",
      hu: "A „Kezdőlap” gomb elrejtése",
      id: "Sembunyikan Tombol 'Beranda'",
      it: "Nascondi il pulsante 'Home'",
      ja: "「ホーム」ボタンを隠す",
      ko: "'홈' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Home'",
      no: "Skjul 'Hjem'-knappen",
      pl: "Ukryj przycisk „Strona główna”",
      pt: "Ocultar o botão 'Home'",
      ro: "Ascundeți butonul „Acasă”",
      ru: "Скрыть кнопку «Домой»",
      sk: "Skryť tlačidlo „Domov“",
      es: "Ocultar el botón 'Inicio'",
      sv: "Dölj 'Hem'-knappen",
      th: "ซ่อนปุ่ม 'หน้าแรก'",
      tr: "'Ana Sayfa' Düğmesini Gizle",
      uk: "Сховати кнопку «Додому»",
      vi: "Ẩn nút 'Trang chủ'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_home",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'البحث'",
      ca: "Amaga el botó 'Cerca'",
      "zh-CN": "隐藏“搜索”按钮",
      "zh-TW": "隱藏“搜尋”按鈕",
      hr: "Sakrij gumb 'Traži'",
      cs: "Skrýt tlačítko „Hledat“",
      da: "Skjul knappen 'Søg'",
      nl: "Knop 'Zoeken' verbergen",
      en: "Hide 'Search' Button",
      fi: "Piilota 'Haku' -painike",
      fr: "Masquer le bouton « Rechercher »",
      de: "Schaltfläche „Suchen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Αναζήτηση»",
      he: "הסתר את לחצן 'חיפוש'",
      hi: "'खोज' बटन छिपाएँ",
      hu: "A „Keresés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Cari'",
      it: "Nascondi il pulsante 'Cerca'",
      ja: "「検索」ボタンを非表示にする",
      ko: "'검색' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Cari'",
      no: "Skjul 'Søk'-knappen",
      pl: "Ukryj przycisk „Szukaj”",
      pt: "Ocultar botão 'Pesquisar'",
      ro: "Ascundeți butonul „Căutare”",
      ru: "Скрыть кнопку «Поиск»",
      sk: "Skryť tlačidlo „Hľadať“",
      es: "Ocultar el botón 'Buscar'",
      sv: "Dölj 'Sök'-knappen",
      th: "ซ่อนปุ่ม 'ค้นหา'",
      tr: "'Ara' Düğmesini Gizle",
      uk: "Сховати кнопку «Пошук»",
      vi: "Ẩn nút 'Tìm kiếm'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_search",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الدردشة'",
      ca: "Amaga el botó 'Xat'",
      "zh-CN": "隐藏“聊天”按钮",
      "zh-TW": "隱藏“聊天”按鈕",
      hr: "Sakrij gumb 'Chat'",
      cs: "Skrýt tlačítko „Chat“",
      da: "Skjul 'Chat'-knap",
      nl: "Knop 'Chat' verbergen",
      en: "Hide 'Chat' Button",
      fi: "Piilota Chat-painike",
      fr: "Masquer le bouton « Chat »",
      de: "Schaltfläche „Chat“ ausblenden",
      el: "Απόκρυψη κουμπιού «Συζήτηση»",
      he: "הסתר את לחצן 'צ'אט'",
      hi: "'चैट' बटन छिपाएँ",
      hu: "A „Csevegés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Obrolan'",
      it: "Nascondi il pulsante 'Chat'",
      ja: "「チャット」ボタンを非表示にする",
      ko: "'채팅' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Sembang'",
      no: "Skjul 'Chat'-knappen",
      pl: "Ukryj przycisk „Czat”",
      pt: "Ocultar botão 'Bate-papo'",
      ro: "Ascundeți butonul „Chat”",
      ru: "Скрыть кнопку «Чат»",
      sk: "Skryť tlačidlo „Rozhovor“",
      es: "Ocultar el botón 'Chat'",
      sv: "Dölj 'Chatt'-knappen",
      th: "ซ่อนปุ่ม 'แชท'",
      tr: "'Sohbet' Düğmesini Gizle",
      uk: "Сховати кнопку «Чат»",
      vi: "Ẩn nút 'Trò chuyện'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_chat",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الإخطارات'",
      ca: "Amaga el botó 'Notificacions'",
      "zh-CN": "隐藏“通知”按钮",
      "zh-TW": "隱藏「通知」按鈕",
      hr: "Sakrij gumb 'Obavijesti'",
      cs: "Skrýt tlačítko 'Oznámení'",
      da: "Skjul knappen 'Meddelelser'",
      nl: "Knop 'Meldingen' verbergen",
      en: "Hide 'Notifications' Button",
      fi: "Piilota Ilmoitukset-painike",
      fr: "Masquer le bouton « Notifications »",
      de: "Schaltfläche „Benachrichtigungen“ ausblenden",
      el: "Απόκρυψη κουμπιού «Ειδοποιήσεις»",
      he: "הסתר את לחצן 'התראות'",
      hi: "'सूचनाएँ' बटन छिपाएँ",
      hu: "Az „Értesítések” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pemberitahuan'",
      it: "Nascondi il pulsante 'Notifiche'",
      ja: "「通知」ボタンを非表示にする",
      ko: "'알림' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Pemberitahuan'",
      no: "Skjul 'Varslinger'-knappen",
      pl: "Ukryj przycisk „Powiadomienia”",
      pt: "Ocultar botão 'Notificações'",
      ro: "Ascundeți butonul „Notificări”",
      ru: "Скрыть кнопку «Уведомления»",
      sk: "Skryť tlačidlo „Upozornenia“",
      es: "Ocultar el botón 'Notificaciones'",
      sv: "Dölj knappen 'Meddelanden'",
      th: "ซ่อนปุ่ม 'การแจ้งเตือน'",
      tr: "'Bildirimler' Düğmesini Gizle",
      uk: "Сховати кнопку «Сповіщення»",
      vi: "Ẩn nút 'Thông báo'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_notifications",
    defaultValue: false,
  },

  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الخلاصات'",
      ca: "Amaga el botó 'Feeds'",
      "zh-CN": "隐藏“提要”按钮",
      "zh-TW": "隱藏「提要」按鈕",
      hr: "Sakrij gumb 'Feeds'",
      cs: "Skrýt tlačítko 'Fedy'",
      da: "Skjul 'Feeds'-knap",
      nl: "Knop 'Feeds' verbergen",
      en: "Hide 'Feeds' Button",
      fi: "Piilota 'Syötteet'-painike",
      fr: "Masquer le bouton « Flux »",
      de: "Schaltfläche „Feeds“ ausblenden",
      el: "Απόκρυψη κουμπιού 'Ροές'",
      he: "הסתר כפתור 'הזנות'",
      hi: "'फ़ीड्स' बटन छिपाएँ",
      hu: "A „Hírcsatornák” gomb elrejtése",
      id: "Sembunyikan Tombol 'Umpan'",
      it: "Nascondi il pulsante 'Feed'",
      ja: "「フィード」ボタンを非表示にする",
      ko: "'피드' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Suapan'",
      no: "Skjul 'Feeds'-knappen",
      pl: "Ukryj przycisk „Kanały”",
      pt: "Ocultar botão 'Feeds'",
      ro: "Ascundeți butonul „Feeduri”",
      ru: "Скрыть кнопку «Ленты»",
      sk: "Skryť tlačidlo „Informačné kanály“",
      es: "Ocultar el botón 'Feeds'",
      sv: "Dölj 'Feeds'-knappen",
      th: "ซ่อนปุ่ม 'ฟีด'",
      tr: "'Yayınlar' Düğmesini Gizle",
      uk: "Сховати кнопку «Канали»",
      vi: "Ẩn nút 'Nguồn cấp dữ liệu'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_feeds",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'القوائم'",
      ca: "Amaga el botó 'Llistes'",
      "zh-CN": "隐藏“列表”按钮",
      "zh-TW": "隱藏“清單”按鈕",
      hr: "Sakrij gumb 'Popisi'",
      cs: "Skrýt tlačítko „Seznamy“",
      da: "Skjul 'Lister'-knap",
      nl: "Knop 'Lijsten' verbergen",
      en: "Hide 'Lists' Button",
      fi: "Piilota Listat-painike",
      fr: "Masquer le bouton « Listes »",
      de: "Schaltfläche „Listen“ ausblenden",
      el: "Κουμπί απόκρυψης 'Λίστες'",
      he: "הסתר כפתור 'רשימות'",
      hi: "'सूचियाँ' बटन छिपाएँ",
      hu: "A „Listák” gomb elrejtése",
      id: "Sembunyikan Tombol 'Daftar'",
      it: "Nascondi il pulsante 'Elenchi'",
      ja: "「リスト」ボタンを非表示にする",
      ko: "'목록' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Senarai'",
      no: "Skjul 'Lister'-knappen",
      pl: "Ukryj przycisk „Listy”",
      pt: "Ocultar botão 'Listas'",
      ro: "Ascundeți butonul „Liste”",
      ru: "Скрыть кнопку «Списки»",
      sk: "Skryť tlačidlo „Zoznamy“",
      es: "Ocultar el botón 'Listas'",
      sv: "Dölj knappen 'Lists'",
      th: "ซ่อนปุ่ม 'รายการ'",
      tr: "'Listeler' Düğmesini Gizle",
      uk: "Приховати кнопку «Списки»",
      vi: "Ẩn nút 'Danh sách'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_lists",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الملف الشخصي'",
      ca: "Amaga el botó 'Perfil'",
      "zh-CN": "隐藏“个人资料”按钮",
      "zh-TW": "隱藏「個人資料」按鈕",
      hr: "Sakrij gumb 'Profil'",
      cs: "Skrýt tlačítko „Profil“",
      da: "Skjul 'Profil'-knap",
      nl: "Knop 'Profiel' verbergen",
      en: "Hide 'Profile' Button",
      fi: "Piilota 'Profiili'-painike",
      fr: "Masquer le bouton « Profil »",
      de: "Schaltfläche „Profil“ ausblenden",
      el: "Κουμπί απόκρυψης 'Προφίλ'",
      he: "הסתר כפתור 'פרופיל'",
      hi: "'प्रोफ़ाइल' बटन छिपाएँ",
      hu: "A „Profil” gomb elrejtése",
      id: "Sembunyikan Tombol 'Profil'",
      it: "Nascondi il pulsante 'Profilo'",
      ja: "「プロフィール」ボタンを非表示にする",
      ko: "'프로필' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Profil'",
      no: "Skjul 'Profil'-knappen",
      pl: "Ukryj przycisk „Profil”",
      pt: "Ocultar botão 'Perfil'",
      ro: "Ascunde butonul „Profil”",
      ru: "Скрыть кнопку «Профиль»",
      sk: "Skryť tlačidlo „Profil“",
      es: "Ocultar botón 'Perfil'",
      sv: "Dölj 'Profil'-knappen",
      th: "ซ่อนปุ่ม 'โปรไฟล์'",
      tr: "'Profil' Düğmesini Gizle",
      uk: "Приховати кнопку «Профіль»",
      vi: "Ẩn nút 'Hồ sơ'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_profile",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'الإعدادات'",
      ca: "Amaga el botó 'Configuració'",
      "zh-CN": "隐藏“设置”按钮",
      "zh-TW": "隱藏“設定”按鈕",
      hr: "Sakrij gumb 'Postavke'",
      cs: "Skrýt tlačítko „Nastavení“",
      da: "Skjul knappen 'Indstillinger'",
      nl: "Knop 'Instellingen' verbergen",
      en: "Hide 'Settings' Button",
      fi: "Piilota Asetukset-painike",
      fr: "Masquer le bouton « Paramètres »",
      de: "Schaltfläche „Einstellungen“ ausblenden",
      el: "Απόκρυψη του κουμπιού 'Ρυθμίσεις'",
      he: "הסתר את לחצן 'הגדרות'",
      hi: "'सेटिंग्स' बटन छिपाएँ",
      hu: "A „Beállítások” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pengaturan'",
      it: "Nascondi il pulsante 'Impostazioni'",
      ja: "「設定」ボタンを非表示にする",
      ko: "'설정' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Tetapan'",
      no: "Skjul 'Innstillinger'-knappen",
      pl: "Ukryj przycisk „Ustawienia”",
      pt: "Ocultar botão 'Configurações'",
      ro: "Ascundeți butonul „Setări”",
      ru: "Скрыть кнопку «Настройки»",
      sk: "Skryť tlačidlo „Nastavenia“",
      es: "Ocultar el botón 'Configuración'",
      sv: "Dölj knappen 'Inställningar'",
      th: "ซ่อนปุ่ม 'การตั้งค่า'",
      tr: "'Ayarlar' Düğmesini Gizle",
      uk: "Сховати кнопку «Налаштування»",
      vi: "Ẩn nút 'Cài đặt'",
    },
    id: "socialFocus_blueSky_navigationBar_hide_button_settings",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قائمة تذييل",
      ca: "Oculta el menú del peu de pàgina",
      "zh-CN": "隐藏页脚菜单",
      "zh-TW": "隱藏頁腳菜單",
      hr: "Sakrij jelovnik podnožja",
      cs: "Skrýt nabídku zápatí",
      da: "Skjul sidefodmenu",
      nl: "Verberg het voettekstmenu",
      en: "Hide Footer Menu",
      fi: "Piilota alatunniste -valikko",
      fr: "Menu de pied de page",
      de: "Fußzeile ausblenden",
      el: "Απόκρυψη μενού υποσέλιδου",
      he: "הסתר תפריט כותרת תחתונה",
      hi: "पाद मेनू छिपाएं",
      hu: "A lábléc elrejtése menü",
      id: "Sembunyikan menu footer",
      it: "Nascondi il menu del piè di pagina",
      ja: "フッターメニューを非表示にします",
      ko: "바닥 글 메뉴를 숨 깁니다",
      ms: "Menyembunyikan menu footer",
      no: "Skjul bunntekstmeny",
      pl: "Ukryj menu stopki",
      pt: "Ocultar o menu do rodapé",
      ro: "Ascunde meniul de subsol",
      ru: "Скрыть меню нижнего колонтитула",
      sk: "Skryť päta menu",
      es: "Ocultar el menú de pie de página",
      sv: "Dölj sidfoteny",
      th: "ซ่อนเมนูส่วนท้าย",
      tr: "Footer Menüsünü Gizle",
      uk: "Меню приховати колонтитул",
      vi: "Ẩn menu chân trang",
    },
    id: "socialFocus_blueSky_navigationBar_hide_menu_footer",
    defaultValue: false,
  },
];

const blueSkyMobileGroups_Other = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء الزر العائم 'منشور جديد'",
      ca: "Amaga el botó flotant 'Nova publicació'",
      "zh-CN": "隐藏“新帖子”浮动按钮",
      "zh-TW": "隱藏「新貼文」浮動按鈕",
      hr: "Sakrij plutajući gumb 'Novi post'",
      cs: "Skrýt plovoucí tlačítko „Nový příspěvek“",
      da: "Skjul 'Nyt indlæg' flydende knap",
      nl: "Zwevende knop 'Nieuw bericht' verbergen",
      en: "Hide 'New Post' Floating Button",
      fi: "Piilota 'Uusi viesti' kelluva painike",
      fr: "Masquer le bouton flottant « Nouveau message »",
      de: "Schwebende Schaltfläche „Neuer Beitrag“ ausblenden",
      el: "Απόκρυψη αιωρούμενου κουμπιού «Νέα ανάρτηση»",
      he: "הסתר את הלחצן הצף 'פוסט חדש'",
      hi: "'नया पोस्ट' फ़्लोटिंग बटन छिपाएँ",
      hu: "Az „Új bejegyzés” lebegő gomb elrejtése",
      id: "Sembunyikan Tombol Mengambang 'Postingan Baru'",
      it: "Nascondi il pulsante mobile 'Nuovo post'",
      ja: "「新規投稿」フローティング ボタンを非表示にする",
      ko: "'새 게시물' 플로팅 버튼 숨기기",
      ms: "Sembunyikan Butang Terapung 'Siaran Baharu'",
      no: "Skjul 'Nytt innlegg' flytende knapp",
      pl: "Ukryj pływający przycisk „Nowy post”",
      pt: "Ocultar botão flutuante 'Nova postagem'",
      ro: "Ascundeți butonul plutitor „Postare nouă”",
      ru: "Скрыть плавающую кнопку «Новое сообщение»",
      sk: "Skryť plávajúce tlačidlo „Nový príspevok“",
      es: "Ocultar el botón flotante 'Nueva publicación'",
      sv: "Dölj 'Nytt inlägg' flytande knapp",
      th: "ซ่อนปุ่มลอย 'โพสต์ใหม่'",
      tr: "'Yeni Gönderi' Kayan Düğmesini Gizle",
      uk: "Сховати плаваючу кнопку «Нова публікація»",
      vi: "Ẩn nút nổi 'Bài đăng mới'",
    },
    id: "socialFocus_twitter_other_hide_floating_new_post",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء قسم البدء",
      ca: "Amaga la secció Introducció",
      "zh-CN": "隐藏入门部分",
      "zh-TW": "隱藏入門部分",
      hr: "Sakrij odjeljak Prvi koraci",
      cs: "Skrýt sekci Začínáme",
      da: "Skjul afsnittet Kom godt i gang",
      nl: "Sectie 'Aan de slag' verbergen",
      en: "Hide Getting Started Section",
      fi: "Piilota Aloitusosio",
      fr: "Masquer la section Mise en route",
      de: "Abschnitt „Erste Schritte“ ausblenden",
      el: "Απόκρυψη ενότητας Ξεκινώντας",
      he: "הסתר את סעיף תחילת העבודה",
      hi: "प्रारंभ करना अनुभाग छिपाएँ",
      hu: "Az Első lépések szakasz elrejtése",
      id: "Sembunyikan Bagian Memulai",
      it: "Nascondi la sezione Per iniziare",
      ja: "「はじめに」セクションを非表示にする",
      ko: "시작하기 섹션 숨기기",
      ms: "Sembunyikan Bahagian Bermula",
      no: "Skjul Komme i gang-delen",
      pl: "Ukryj sekcję Pierwsze kroki",
      pt: "Ocultar seção de primeiros passos",
      ro: "Ascundeți secțiunea Introducere",
      ru: "Скрыть раздел «Начало работы»",
      sk: "Skryť sekciu Začíname",
      es: "Ocultar sección de introducción",
      sv: "Dölj avsnittet Komma igång",
      th: "ซ่อนส่วนการเริ่มต้นใช้งาน",
      tr: "Başlarken Bölümünü Gizle",
      uk: "Приховати розділ «Початок роботи»",
      vi: "Ẩn phần Bắt đầu",
    },
    id: "socialFocus_blueSky_others_hide_getting_started_section",
    defaultValue: false,
  },
];

// MARK: - Mobile Builder

const blueSkyMobileGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "blueSky",
    options: [blueSkyMobileGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "blueSky",
    options: blueSkyMobileGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "blueSky",
    options: blueSkyMobileGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "الصفحة الرئيسية",
      ca: "Pàgina d'inici",
      "zh-CN": "主页",
      "zh-TW": "首頁",
      hr: "Početna stranica",
      cs: "Domovská stránka",
      da: "Hjemmeside",
      nl: "Startpagina",
      en: "Home Page",
      fi: "Kotisivu",
      fr: "Page d'accueil",
      de: "Startseite",
      el: "Αρχική Σελίδα",
      he: "דף הבית",
      hi: "होम पेज",
      hu: "Kezdőlap",
      id: "Halaman Beranda",
      it: "Pagina iniziale",
      ja: "ホームページ",
      ko: "홈 페이지",
      ms: "Halaman Utama",
      no: "Hjemmeside",
      pl: "Strona główna",
      pt: "Pagina inicial",
      ro: "Pagina principala",
      ru: "Домашняя страница",
      sk: "Domovská stránka",
      es: "Página de inicio",
      sv: "Hemsida",
      th: "หน้าแรก",
      tr: "Ana Sayfa",
      uk: "Домашня сторінка",
      vi: "Trang chủ",
    },
    groupId: "feed",
    parentCategoryId: "blueSky",
    options: blueSkyMobileGroups_Feed,
  },
  {
    groupName: {
      ar: "دعامات",
      ca: "Publicacions",
      "zh-CN": "帖子",
      "zh-TW": "貼文",
      hr: "Postovi",
      cs: "Příspěvky",
      da: "Indlæg",
      nl: "Berichten",
      en: "Posts",
      fi: "Viestit",
      fr: "Des postes",
      de: "Beiträge",
      el: "Αναρτήσεις",
      he: "פוסטים",
      hi: "पदों",
      hu: "Hozzászólások",
      id: "Postingan",
      it: "Messaggi",
      ja: "投稿",
      ko: "게시물",
      ms: "Catatan",
      no: "Innlegg",
      pl: "Posty",
      pt: "Postagens",
      ro: "Postări",
      ru: "Сообщения",
      sk: "Príspevky",
      es: "Publicaciones",
      sv: "Inlägg",
      th: "กระทู้",
      tr: "Gönderiler",
      uk: "Пости",
      vi: "Bài viết",
    },
    groupId: "post",
    parentCategoryId: "blueSky",
    options: blueSkyMobileGroups_Post,
  },
  {
    groupName: {
      ar: "شريط التنقل",
      ca: "Barra de navegació",
      "zh-CN": "导航栏",
      "zh-TW": "導覽列",
      hr: "Navigacijska traka",
      cs: "Navigační lišta",
      da: "Navigations bar",
      nl: "Navigatiebalk",
      en: "Navigation Bar",
      fi: "Navigointipalkki",
      fr: "Barre de navigation",
      de: "Navigationsleiste",
      el: "Μπάρα πλοήγησης",
      he: "סרגל ניווט",
      hi: "नेविगेशन पट्टी",
      hu: "Navigációs sáv",
      id: "Bilah Navigasi",
      it: "Barra di navigazione",
      ja: "ナビゲーションバー",
      ko: "네비게이션 바",
      ms: "Bar navigasi",
      no: "Navigasjonslinje",
      pl: "Pasek nawigacyjny",
      pt: "Barra de navegação",
      ro: "Bară de navigare",
      ru: "Панель навигации",
      sk: "Navigačná lišta",
      es: "Barra de navegación",
      sv: "Navigeringsfält",
      th: "แถบนำทาง",
      tr: "Gezinti çubuğu",
      uk: "Панель навігації",
      vi: "Thanh điều hướng",
    },
    groupId: "navigationBar",
    parentCategoryId: "blueSky",
    options: blueSkyMobileGroups_NavigationBar,
  },

  {
    groupName: {
      ar: "آحرون",
      ca: "Altres",
      "zh-CN": "其他的",
      "zh-TW": "其他的",
      hr: "Drugi",
      cs: "Ostatní",
      da: "Andre",
      nl: "Anderen",
      en: "Others",
      fi: "Muut",
      fr: "Autres",
      de: "Andere",
      el: "Οι υπολοιποι",
      he: "אחרים",
      hi: "अन्य",
      hu: "Mások",
      id: "Yang lain",
      it: "Altri",
      ja: "その他",
      ko: "기타",
      ms: "Lain-lain",
      no: "Andre",
      pl: "Inni",
      pt: "Outros",
      ro: "Alții",
      ru: "Другие",
      sk: "Iní",
      es: "Otros",
      sv: "Andra",
      th: "คนอื่น",
      tr: "Diğerleri",
      uk: "Інші",
      vi: "Người khác",
    },
    groupId: "other",
    parentCategoryId: "blueSky",
    options: blueSkyMobileGroups_Other,
  },
];
